/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "audiolib_constants.h"

namespace audiolib {

const audiolibConstants g_audiolib_constants;

audiolibConstants::audiolibConstants() {
}

} // namespace

