/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef audiolib_CONSTANTS_H
#define audiolib_CONSTANTS_H

#include "audiolib_types.h"

namespace audiolib {

class audiolibConstants {
 public:
  audiolibConstants();

};

extern const audiolibConstants g_audiolib_constants;

} // namespace

#endif
