LIB_SRC = 			\
	Acceptor.cc		\
	Channel.cc		\
	EventLoop.cc		\
	EventLoopThread.cc	\
	InetAddress.cc		\
	Poller.cc		\
	Socket.cc		\
	SocketsOps.cc		\
	TcpConnection.cc	\
	TcpServer.cc		\
	Timer.cc		\
	TimerQueue.cc

BINARIES = test1 test2 test3 test4 test5 test6 test7 test8

all: $(BINARIES)

include ../reactor_lib.mk

test1: tests/test1.cc
test2: tests/test2.cc
test3: tests/test3.cc
test4: tests/test4.cc
test5: tests/test5.cc
test6: tests/test6.cc
test7: tests/test7.cc
test8: tests/test8.cc
