/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef imagelib_CONSTANTS_H
#define imagelib_CONSTANTS_H

#include "imagelib_types.h"

namespace imagelib {

class imagelibConstants {
 public:
  imagelibConstants();

};

extern const imagelibConstants g_imagelib_constants;

} // namespace

#endif
