/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "imagelib_constants.h"

namespace imagelib {

const imagelibConstants g_imagelib_constants;

imagelibConstants::imagelibConstants() {
}

} // namespace

